{
 "title": "Cost / Efficiency Signals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Shared Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total{tier=\"free\"}[1m])) \n/ \n(clamp_min(\n  sum(kube_deployment_status_replicas_available{deployment=~\"shared-worker\"}),\n   1)\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests per VIP Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total{tier=\"vip\"}[1m])) / (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"vip-worker\"}), 1))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency vs Shared Worker Replicas",
   "type": "timeseries",
   "description": "worker end-to-end job processing latency vs number of shared worker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (rate(worker_processing_latency_seconds_bucket{tier=\"free\"}[5m])) \n)",
     "legendFormat": "P95 latency ( seconds ) "
    },
    {
     "expr": "sum(\n  kube_deployment_status_replicas_available{deployment=\"shared-worker\"}\n)",
     "legendFormat": "Shared worker replica ( num )"
    }
   ]
  },
  {
   "title": "P95 Latency vs VIP Worker Replicas",
   "type": "timeseries",
   "description": "worker end-to-end job processing latency vs number of VIP worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (rate(worker_processing_latency_seconds_bucket{tier=\"vip\"}[5m])) \n)",
     "legendFormat": "P95 latency ( seconds ) "
    },
    {
     "expr": "sum(\n  kube_deployment_status_replicas_available{deployment=\"vip-worker\"}\n)",
     "legendFormat": "VIP worker replica ( num )"
    }
   ]
  },
  {
   "title": "Requests per Triton Replica ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_request_success[1m])) \n/ \n(clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"triton\"}), \n1))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Triton Effective Batch Size ",
   "type": "timeseries",
   "description": "1.0  = no batching\n4.0  = average batch size 4\n8.0  = near max batch size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m])) \n/ clamp_min(\n  (sum (rate(nv_inference_exec_count{model=\"transaction_anomaly_detector\"}[1m]))),\n  0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Queue Depth per Shared Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "num/replica" } },
   "targets": [
    {
     "expr": "sum(inference_queue_depth{tier=\"free\"})/ (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"shared-worker\"}), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Tier Queue Depth per VIP Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "num/replica" } },
   "targets": [
    {
     "expr": "sum(inference_queue_depth{tier=\"vip\"}) / (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"vip-worker\"}), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Seconds per Processed Request - Shared Worker",
   "type": "timeseries",
   "description": "Average CPU seconds used per processed request. Only show this metric if there were enough requests to make the ratio meaningful.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "core-s / req" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{app=\"shared-worker\"}[10m]))\n/\nsum(increase(processed_requests_total{tier=\"free\"}[10m]))\nand\nsum(increase(processed_requests_total{tier=\"free\"}[10m])) > 10",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Seconds per Processed Request - VIP Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "core-s / req" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{app=\"vip-worker\"}[10m]))\n/\nsum(increase(processed_requests_total{tier=\"vip\"}[10m]))\nand\nsum(increase(processed_requests_total{tier=\"vip\"}[10m])) > 10",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}