{
 "title": "Reliability ",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "API Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (\n  rate(fastapi_request_count_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, endpoint) (\n    rate(fastapi_request_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(app_errors_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "4xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint, status) (\n  rate(app_errors_total{status=~\"4..\"}[1m])\n)",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint, status) (\n  rate(app_errors_total{status=~\"5..\"}[1m])\n)",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  },
  { "title": "Redis Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Circuit Breakers Currently Open",
   "type": "timeseries",
   "description": "CircuitBreakerState.CLOSED = 0\nCircuitBreakerState.OPEN = 1\nCircuitBreakerState.HALF_OPEN = 2 ",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "count(redis_circuit_breaker_state == 1)",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "Circuit breaker state (closed = 0, open = 1, half_open = 2)",
   "type": "timeseries",
   "description": "CircuitBreakerState.CLOSED = 0\nCircuitBreakerState.OPEN = 1\nCircuitBreakerState.HALF_OPEN = 2 ",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 26 },
   "targets": [
    {
     "expr": "max by (operation) (\n  redis_circuit_breaker_state\n)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Queue Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Queue Wait P95 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, tier) (rate(queue_wait_latency_seconds_bucket[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Depth ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(tier) (inference_queue_depth)",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Queue Ingress Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(queue_ingress_total[1m])) by (tier)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Processed Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total[1m])) by (tier)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Backlog Growth Rate",
   "type": "timeseries",
   "description": "positive value = queue is growing\n\nnear zero = workers are keeping up\n\nnegative value = workers are draining backlog",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (tier) (\n  rate(queue_ingress_total[1m])\n)\n-\nsum by (tier) (\n  rate(processed_requests_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Worker Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Worker processing P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95, \n  sum by (le,tier) (\n    rate(worker_processing_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Failure Rate by Tier and Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(tier, stage) (rate(worker_processing_failures_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Failure Rate by Stage and Error Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (stage, error_type) (\n  rate(worker_processing_failures_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker → Triton Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (model_name, model_version, error_type) (\n  rate(worker_processing_failures_total{stage=\"triton_request\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DLQ Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "DLQ Jobs Total by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(reason) (dlq_jobs_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ Jobs Rate by reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(dlq_jobs_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ Push Attempts rate by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(reason) (\n  rate(dlq_push_attempt_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Payload DLQ Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(dlq_jobs_total{reason=\"invalid_job_payload\"}[1m]))",
     "legendFormat": "invalid_job_payload"
    }
   ]
  },
  {
   "title": "DLQ Push Failure Rate by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(dlq_push_failure_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Triton Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Triton Request Failure Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_request_failure[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Request Success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_request_success[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Triton Request Latency by Model/Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_request_duration_us[1m])\n)\n/\nclamp_min(\n  sum by(model, version) (\n    rate(nv_inference_request_success[1m])\n  ),\n  0.001\n)\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Infrastructure Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Kubernetes Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum by (pod, container) (\n  increase(kube_pod_container_status_restarts_total{\n    namespace=\"default\",\n    pod=~\"anomaly-inference-system.*|shared-worker.*|vip-worker.*|triton.*|redis.*\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anomaly inference System Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"anomaly-inference-system-hpa\"}\n\n",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"anomaly-inference-system-hpa\"}",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"anomaly-inference-system-hpa\"}",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"anomaly-inference-system-hpa\"}",
     "legendFormat": "Max Replicas"
    }
   ]
  },
  {
   "title": "Shared Worker Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"keda-hpa-shared-worker-scaledobject\"}",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"keda-hpa-shared-worker-scaledobject\"}",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"keda-hpa-shared-worker-scaledobject\"}",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"keda-hpa-shared-worker-scaledobject\"}",
     "legendFormat": "Max Replicas"
    }
   ]
  },
  {
   "title": "Triton Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"keda-hpa-triton-scaledobject\"}",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"keda-hpa-triton-scaledobject\"}",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"keda-hpa-triton-scaledobject\"}",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"keda-hpa-triton-scaledobject\"}",
     "legendFormat": "Max Replicas"
    }
   ]
  },
  {
   "title": "VIP Worker Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"keda-hpa-vip-worker-scaledobject\"}",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"keda-hpa-vip-worker-scaledobject\"}",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"keda-hpa-vip-worker-scaledobject\"}",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"keda-hpa-vip-worker-scaledobject\"}",
     "legendFormat": "Max Replicas"
    }
   ]
  },
  {
   "title": "Pod Readiness and Available Replicas",
   "type": "timeseries",
   "description": "1 = pod is ready\n0 = pod is not ready",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "max by (pod) (\n  kube_pod_status_ready{\n    namespace=\"default\",\n    condition=\"true\",\n    pod=~\"anomaly-inference-system.*|shared-worker.*|vip-worker.*|triton.*|redis.*\"\n  }\n)",
     "legendFormat": "{{pod}} ready"
    },
    {
     "expr": "sum by (deployment) (\n  kube_deployment_status_replicas_available{\n    namespace=\"default\",\n    deployment=~\"anomaly-inference-system|shared-worker|vip-worker|triton|redis\"\n  }\n)",
     "legendFormat": "{{deployment}} available"
    }
   ]
  }
 ]
}