{
 "title": "Triton Inference Overview - with Versions",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Triton Traffic & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Triton Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(nv_inference_exec_count{model=\"transaction_anomaly_detector\"}[1m]))",
     "legendFormat": "model executed {{version}}"
    },
    {
     "expr": "sum by (version) (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m]))",
     "legendFormat": "success request {{version}}"
    }
   ]
  },
  {
   "title": "Inference Count",
   "type": "timeseries",
   "description": "to track the total cumulative number of successful inference requests processed by transaction_anomaly_detector model.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(nv_inference_count{model=\"transaction_anomaly_detector\"}[1m]))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  {
   "title": "Triton Avg Request Latency (End to End)",
   "type": "timeseries",
   "description": "End-to-end request handling latency inside the Triton Inference Server ( Queue + Compute Input + Compute Infer + Compute Output) ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(version) (rate(nv_inference_request_duration_us{model=\"transaction_anomaly_detector\"}[1m]) / 1000)) / (sum by(version) (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  {
   "title": "Triton Avg Infer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(version) (rate(nv_inference_compute_infer_duration_us{model=\"transaction_anomaly_detector\"}[1m]) / 1000)) / (sum by(version) (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  {
   "title": "Triton Avg Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by(version) (rate(nv_inference_queue_duration_us{model=\"transaction_anomaly_detector\"}[1m]) / 1000)) / (sum by(version) (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  {
   "title": "Triton Avg Compute Input Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by(version) (rate(nv_inference_compute_input_duration_us{model=\"transaction_anomaly_detector\"}[1m]) / 1000)) / (sum by(version) (rate(nv_inference_count{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version{{version}}"
    }
   ]
  },
  {
   "title": "Triton Avg Compute Output Latency",
   "type": "timeseries",
   "description": "backend\n\n↓\n\nresponse tensor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (version) (rate(nv_inference_compute_output_duration_us{model=\"transaction_anomaly_detector\"}[1m]))\n/\nsum by (version) (rate(nv_inference_count{model=\"transaction_anomaly_detector\"}[1m]))\n/\n1000",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  {
   "title": "Queue Ratio",
   "type": "timeseries",
   "description": "backend\n\n↓\n\nresponse tensor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(nv_inference_queue_duration_us{model=\"transaction_anomaly_detector\"}[1m])) / (sum by(version) (rate(nv_inference_request_duration_us{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  { "title": "Dynamic Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Worker Max Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(tier) (current_batch_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Max Batch Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(tier) (current_batch_timeout_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Effective Batch Size ",
   "type": "timeseries",
   "description": "1.0  = no batching\n4.0  = average batch size 4\n8.0  = near max batch size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(nv_inference_request_success{model=\"transaction_anomaly_detector\"}[1m])) / (sum by(version) (rate(nv_inference_exec_count{model=\"transaction_anomaly_detector\"}[1m])))",
     "legendFormat": "model_version {{version}}"
    }
   ]
  },
  { "title": "Worker -> Triton Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Worker Serialization P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(worker_triton_serialization_seconds_bucket{model_name=\"transaction_anomaly_detector\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Deserialization P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(worker_triton_deserialization_seconds_bucket{model_name=\"transaction_anomaly_detector\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker -> Triton  P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(worker_triton_request_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Processing Latency P95",
   "type": "timeseries",
   "description": "to track the total cumulative number of successful inference requests processed by anomaly_detector model.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(worker_processing_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}