name: anomaly-inference-system
services:

  redis_sync:
    image: redis:7-alpine
    container_name: redis_sync
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  redis_inference:
    image: redis:7-alpine
    container_name: redis_inference
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  vip_worker1:
    build: .
    # command: what process the container should run when it starts
    command: python3 -m app.model.worker
    container_name: vip_worker1
    environment:
      - WORKER_ROLE=vip
      - WORKER_ID=1
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  vip_worker2:
    build: .
    command: python3 -m app.model.worker
    container_name: vip_worker2
    environment:
      - WORKER_ROLE=vip
      - WORKER_ID=2
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  vip_worker3:
    build: .
    # command: what process the container should run when it starts
    command: python3 -m app.model.worker
    container_name: vip_worker3
    environment:
      - WORKER_ROLE=vip
      - WORKER_ID=3
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  shared_worker1:
    build: .
    command: python3 -m app.model.worker
    container_name: shared_worker1
    environment:
      - WORKER_ROLE=shared
      - WORKER_ID=1
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  shared_worker2:
    build: .
    command: python3 -m app.model.worker
    container_name: shared_worker2
    environment:
      - WORKER_ROLE=shared
      - WORKER_ID=2
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  shared_worker3:
    build: .
    command: python3 -m app.model.worker
    container_name: shared_worker3
    environment:
      - WORKER_ROLE=shared
      - WORKER_ID=3
      - REDIS_INFERENCE_HOST=redis-inference
      - REDIS_INFERENCE_PORT=6379
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  autoscaler:
    build: .
    command: python3 -m app.model.run_autoscaler
    depends_on:
      - redis_inference
    networks:
      - appnet
    restart: unless-stopped

  # three copies of your app
  app1:
    build: .
    container_name: app1
    labels:
      - "service=app1"
    environment:
      - INSTANCE_ID=app1
      - LOG_FORMAT=pretty
      - REDIS_SYNC_HOST=redis_sync
      - REDIS_SYNC_PORT=6379
    networks:
      - appnet
    depends_on:
      - redis_sync
    # volumes: mount host machine directory into container filesystem
    volumes:
      - .:/app

  app2:
    build: .
    container_name: app2
    labels:
      - "service=app2"
    environment:
      - INSTANCE_ID=app2
      - LOG_FORMAT=pretty
      - REDIS_SYNC_HOST=redis_sync
      - REDIS_SYNC_PORT=6379
    networks:
      - appnet
    depends_on:
      - redis_sync
    volumes:
      - .:/app

  app3:
    build: .
    container_name: app3
    labels:
      - "service=app3"
    environment:
      - INSTANCE_ID=app3
      - LOG_FORMAT=pretty
      - REDIS_SYNC_HOST=redis_sync
      - REDIS_SYNC_PORT=6379
    networks:
      - appnet
    depends_on:
      - redis_sync
    volumes:
      - .:/app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"     # host:container
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - appnet
    # localhost:8000 → nginx:80 → appX:8000

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx_exporter
    command:
      - -nginx.scrape-uri=http://nginx_proxy/nginx-status
    ports:
      - "9114:9113"
    depends_on:
      - nginx
    networks:
      - appnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin333
      - GF_SECURITY_ADMIN_PASSWORD=admin333
    networks:
      - appnet

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  grafana-storage: