apiVersion: apps/v1
kind: Deployment

metadata:
  name: anomaly-inference-system

spec:
  replicas: 3

  selector:
    matchLabels:
      app: anomaly-inference-system

  template:
    metadata:
      labels:
        app: anomaly-inference-system

    spec:
      containers:
        - name: anomaly-inference-container
          image: anomaly-inference-system:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: anomaly-inference-config
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /live
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              #1000m = 1 CPU core
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

