apiVersion: v1
kind: Service

metadata:
  name: anomaly-inference-service

spec:
  selector:
    app: anomaly-inference-system

  ports:
    - protocol: TCP
      # service port (for external communication)
      port: 80
      # pod port (internal communication)
      targetPort: 8000

  type: LoadBalancer
