apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-sync

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis-sync

  template:
    metadata:
      labels:
        app: redis-sync

    spec:
      containers:
        - name: redis
          image: redis:7-alpine

          ports:
            - containerPort: 6379