apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vip-worker-scaledobject

spec:
  scaleTargetRef:
    name: vip-worker

  minReplicaCount: 2
  maxReplicaCount: 3

  triggers:
    - type: redis
      metadata:
        address: redis.default.svc.cluster.local:6379
        listName: vip_jobs
        listLength: "150"

    - type: prometheus
      metadata:
        serverAddress: http://prometheus-service.default.svc.cluster.local:9090
        metricName: worker_processing_latency_p95
        query: |
          histogram_quantile(
            0.95, 
            sum by(le) (rate(worker_processing_latency_seconds_bucket{worker_role="vip"}[5m]))
          )
        threshold: "0.6"

    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
