{
 "title": "Anomaly Inference System - Autoscaling ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(tier)(rate(queue_ingress_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Requests Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(tier) (rate(processed_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Throughput Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total{tier=\"free\"}[1m]))\n/\nsum(rate(processed_requests_total[1m]))",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(tier) (inference_queue_depth)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Wait Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(\n    0.95, \n    sum by (tier,le) (rate(queue_wait_latency_seconds_bucket[5m]))\n )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Pressure Ratio",
   "type": "timeseries",
   "description": "<1\tdraining\n=1\tstable\n>1\tbacklog growing",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(queue_ingress_total)\n/\nsum(processed_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(tier) (current_batch_size)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Wait Time/Timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(tier) (current_batch_timeout_seconds)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Processing Latency P95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum by(le, tier)(rate(worker_processing_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Occupancy / Inference Processing Utilization",
     "type": "timeseries",
     "description": "average busy time per worker.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(worker_role)(rate(worker_processing_latency_seconds_sum[1m]))\n/\ncount by(worker_role)(workers_active_state==1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Worker Active State",
     "type": "timeseries",
     "description": "VERY important autoscaler propagation visibility.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "group by(worker_role, worker_id) (workers_active_state)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Shared Worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 36 },
     "targets": [
      { "expr": "active_shared_workers", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Active VIP Worker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
     "targets": [
      { "expr": "active_vip_workers", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Scaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Scaling Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (tier, direction)(\n  increase(scaling_events_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Container CPU",
     "type": "timeseries",
     "description": "VERY important saturation metric",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(\n  rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])\n)",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Per Container CPU Usage",
     "type": "timeseries",
     "description": "VERY important hotspot visibility.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum by (id)(\n  rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[1m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum (\n  container_memory_usage_bytes{id=~\"/docker/.*\"}\n)/1024/1024",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Per Container Memory Usage",
     "type": "timeseries",
     "description": "VERY important hotspot visibility.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum by (id)(\n  container_memory_usage_bytes{id=~\"/docker/.*\"}\n)/1024/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container Count",
     "type": "timeseries",
     "description": "VERY important elasticity visibility.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "count(container_last_seen{id=~\"/docker/.*\"})",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}