{
 "title": "Cost / Efficiency Signals",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Shared Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total{tier=\"free\"}[1m])) \n/ \n(clamp_min(\n  sum(kube_deployment_status_replicas_available{deployment=~\"shared-worker\"}),\n   1)\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests per VIP Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(processed_requests_total{tier=\"vip\"}[1m])) / (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"vip-worker\"}), 1))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency vs Shared Worker Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (rate(worker_processing_latency_seconds_bucket{tier=\"free\"}[5m])) \n)",
     "legendFormat": "P95 latency ( seconds ) "
    },
    {
     "expr": "sum(\n  kube_deployment_status_replicas_available{deployment=\"shared-worker\"}\n)",
     "legendFormat": "Shared worker replica ( num )"
    }
   ]
  },
  {
   "title": "P95 Latency vs Shared Worker Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by(le) (rate(worker_processing_latency_seconds_bucket{tier=\"vip\"}[5m])) \n)",
     "legendFormat": "P95 latency ( seconds ) "
    },
    {
     "expr": "sum(\n  kube_deployment_status_replicas_available{deployment=\"vip-worker\"}\n)",
     "legendFormat": "Shared worker replica ( num )"
    }
   ]
  },
  {
   "title": "Requests per Triton Replica ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s/replica" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_request_success[1m])) / (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"triton\"}), 1))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Max Batch Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(tier) (current_batch_size)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Queue Depth per Shared Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "num/replica" } },
   "targets": [
    {
     "expr": "sum(inference_queue_depth{tier=\"free\"})/ (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"shared-worker\"}), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Tier Queue Depth per VIP Worker Replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "num/replica" } },
   "targets": [
    {
     "expr": "sum(inference_queue_depth{tier=\"vip\"}) / (clamp_min(sum(kube_deployment_status_replicas_available{deployment=~\"vip-worker\"}), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cost per Request - Shared Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "core -s / req" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(process_cpu_seconds_total{app=\"shared-worker\"}[5m]))\n  /\n  sum(rate(processed_requests_total{tier=\"free\"}[5m]))\n)\nand\nsum(rate(processed_requests_total{tier=\"free\"}[5m])) > 0.01",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Cost per Request - VIP Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "core-s / req" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(process_cpu_seconds_total{app=\"vip-worker\"}[5m]))\n  /\n  sum(rate(processed_requests_total{tier=\"vip\"}[5m]))\n)\nand\nsum(rate(processed_requests_total{tier=\"vip\"}[5m])) > 0.01",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}