{
 "title": "Model Version Comparison",
 "time": { "from": "2026-07-07T22:42:06.309Z", "to": "2026-07-07T23:00:15.514Z" },
 "panels": [
  { "title": "Model Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction Agreement Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(prediction_agreement_total{model_name=\"anomaly_detector\"}[1m]))",
     "legendFormat": "model version 1 &  model version 2 "
    }
   ]
  },
  {
   "title": "Prediction Agreement Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prediction_disagreement_total{model_name=\"anomaly_detector\"}[5m]))",
     "legendFormat": "model version 1 &  model version 2 "
    }
   ]
  },
  {
   "title": "Anomaly Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(prediction_result_total{model_version=\"1\", result=\"anomaly\"}[5m])) / (sum(rate(prediction_result_total{model_version=\"1\"}[5m])))",
     "legendFormat": "model version 1"
    },
    {
     "expr": "sum(rate(prediction_result_total{model_version=\"2\", result=\"anomaly\"}[5m])) / (sum(rate(prediction_result_total{model_version=\"2\"}[5m])))",
     "legendFormat": "model version 2"
    }
   ]
  },
  {
   "title": "Prediction Score Distribution (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prediction_score_bucket{model_version=\"1\", model_name=\"anomaly_detector\"}[5m])))",
     "legendFormat": "model version 1"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prediction_score_bucket{model_version=\"2\", model_name=\"anomaly_detector\"}[5m])))",
     "legendFormat": "model version 2"
    }
   ]
  },
  {
   "title": "Prediction Score Difference P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le) (\n    rate(prediction_score_diff_bucket{model_name=\"anomaly_detector\"}[5m])\n  )\n)",
     "legendFormat": "model version 1"
    }
   ]
  }
 ]
}