{
 "title": "Model Inference Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Model Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model Inference Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(tier, model_version) (\n  rate(model_inference_requests_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Inference Latency P95 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le, tier, model_version) (\n    rate(model_inference_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Model Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Model Load Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, model_version) (model_load_time_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Load Time",
   "type": "stat",
   "description": "model load is a lifecycle/startup event,\nnot continuous traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, model_version) (model_load_time_seconds_sum) / (sum by(kubernetes_pod_name, model_version) (model_load_time_seconds_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queue + Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Queue Wait Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(queue_wait_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Processing Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(worker_processing_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batching ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Configured Batch Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(tier) (current_batch_timeout_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Batch Size P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier) (rate(model_batch_size_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average batch size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(tier) (rate(model_batch_size_sum[5m]))\n/\nsum by(tier) (rate(model_batch_size_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "503 Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_request_count_total{status=\"503\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts Last 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod, container) (\n  increase(kube_pod_container_status_restarts_total[1h])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}