{
 "title": "Anomaly Inference System - Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Accepted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Handled Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}