{
 "title": "Triton Inference Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Triton Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nv_inference_exec_count[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(nv_inference_request_success[1m])",
     "legendFormat": "success "
    },
    {
     "expr": "rate(nv_inference_request_failure[1m])",
     "legendFormat": "failure "
    }
   ]
  },
  {
   "title": "Triton Avg Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us{model=\"anomaly_detector\"}[1m])\n/\nrate(nv_inference_request_success{model=\"anomaly_detector\"}[1m])\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Avg Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{model=\"anomaly_detector\"}[1m])\n/\nrate(nv_inference_request_success{model=\"anomaly_detector\"}[1m])\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Avg Compute Infer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{model=\"anomaly_detector\"}[1m])\n/\nrate(nv_inference_count{model=\"anomaly_detector\"}[1m])\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(nv_inference_count[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker -> Triton  P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier, model_name) (rate(worker_triton_request_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Serialization P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier, model_name) (rate(worker_triton_serialization_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Deserialization P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, tier, model_name) (rate(worker_triton_deserialization_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Avg Compute Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_input_duration_us{model=\"anomaly_detector\"}[1m])\n/\nrate(nv_inference_count{model=\"anomaly_detector\"}[1m])\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triton Avg Compute Output",
   "type": "timeseries",
   "description": "backend\n\n↓\n\nresponse tensor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_output_duration_us{model=\"anomaly_detector\"}[1m])\n/\nrate(nv_inference_count{model=\"anomaly_detector\"}[1m])\n/\n1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Ratio",
   "type": "timeseries",
   "description": "backend\n\n↓\n\nresponse tensor",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\nrate(nv_inference_queue_duration_us{model=\"anomaly_detector\"}[1m])\n)\n/\n(\nrate(nv_inference_request_duration_us{model=\"anomaly_detector\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}